build deploy done?

diff --git a/.github/workflows/build-deploy.yml b/.github/workflows/build-deploy.yml
--- a/.github/workflows/build-deploy.yml
+++ b/.github/workflows/build-deploy.yml
@@ -11,20 +11,17 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-
       - name: Use Node 22
         uses: actions/setup-node@v4
         with:
           node-version: 22
 
-      - name: Install frontend dependencies
+      - name: Install frontend
         run: npm ci
         working-directory: frontend
-
       - name: Build frontend
         run: npm run onlybuild
         working-directory: frontend
-
       - name: Copy build artifacts
         run: |
           mkdir -p backend/express/spa
@@ -36,7 +33,6 @@ jobs:
         with:
           username: ${{ secrets.DOCKERHUB_NAME }}
           password: ${{ secrets.DOCKERHUB_PAT }}
-
       - name: Build and push to Docker Hub
         run: |
           IMG=${{ secrets.DOCKERHUB_NAME }}/my-express:latest
@@ -44,29 +40,28 @@ jobs:
           docker push $IMG
         working-directory: backend
 
-  # deploy:
-  #   needs: build-and-push # This job will only run if build-and-push succeeds
-  #   runs-on: ubuntu-latest
-  #   environment: production
-  #   steps:
-  #     - name: Checkout
-  #       uses: actions/checkout@v4
+  deploy:
+    needs: build-and-push
+    runs-on: ubuntu-latest
+    environment: production
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
 
-  #     - name: Deploy to Digital Ocean
-  #       uses: appleboy/ssh-action@master
-  #       with:
-  #         host: ${{ secrets.DEPLOY_HOST }}
-  #         username: ${{ secrets.DEPLOY_USER }}
-  #         key: ${{ secrets.DEPLOY_KEY }}
-  #         script: |
-  #           APP_DIR="/root/git/server"
-  #           cd $APP_DIR || { echo "$APP_DIR does not exist"; exit 1; }
+      - name: Deploy to Digital Ocean
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.DEPLOY_HOST }}
+          username: ${{ secrets.DEPLOY_USER }}
+          key: ${{ secrets.DEPLOY_KEY }}
+          script: |
+            cd /root/git/server || { echo "dir does not exist"; exit 1; }
             
-  #           git pull origin build || { echo "Git pull failed"; exit 1; } 
-  #           echo "${{ secrets.DOCKERHUB_PAT }}" | docker login -u ${{ secrets.DOCKERHUB_NAME }} --password-stdin || { echo "Docker login failed"; exit 1; }
+            git pull origin build || { echo "Git pull failed"; exit 1; } 
+            echo "${{ secrets.DOCKERHUB_PAT }}" | docker login -u ${{ secrets.DOCKERHUB_NAME }} --password-stdin || { echo "Docker login failed"; exit 1; }
             
-  #           docker compose -f docker-compose.prod.yml pull || { echo "Docker compose pull failed"; exit 1; }
-  #           docker compose -f docker-compose.prod.yml up -d --remove-orphans || { echo "Docker compose up failed"; exit 1; }
+            docker compose -f docker-compose.prod.yml pull || { echo "Docker compose pull failed"; exit 1; }
+            docker compose -f docker-compose.prod.yml up -d --remove-orphans || { echo "Docker compose up failed"; exit 1; }
+            docker logout
             
-  #           echo "Deployment success!"
-  #           docker logout
+            echo "Deployment success!"
